cluster = ["ubuntu24.04 x3"]
max_clusters = 3
base_runbooks = ["antrieb/primer", "antrieb/networking-primer"]
control_node = "node1"
endpoint = "https://antrieb.sh/mcp"

[[networks]]
name = "messaging"
dhcp = true
egress = true

[nics]
node1 = [{ net = "messaging" }]
node2 = [{ net = "messaging" }]
node3 = [{ net = "messaging" }]
