[vyos_routers]
node1 ansible_host=10.100.9.10 ansible_user=vyos ansible_connection=ssh ansible_become=yes ansible_become_method=sudo ansible_become_user=root

[linux_hosts]
node2 ansible_host=10.100.9.11 ansible_user=root vlan_id=10 vlan_ip=10.10.10.2/24 peer_subnet=10.10.20.0/24 vlan_gateway=10.10.10.1
node3 ansible_host=10.100.9.12 ansible_user=root vlan_id=20 vlan_ip=10.10.20.2/24 peer_subnet=10.10.10.0/24 vlan_gateway=10.10.20.1

[all:vars]
ansible_ssh_private_key_file=~/.ssh/cluster_ed25519
ansible_python_interpreter=/usr/bin/python3
