[router]
node1 ansible_host=10.100.205.10 ansible_user=vyos ansible_network_os=vyos.vyos.vyos

[lan_a]
node2 ansible_host=10.100.205.11 ansible_user=root

[lan_b]
node3 ansible_host=10.100.205.12 ansible_user=root

[lan_a:vars]
segment_iface=enp8s0
segment_addr=10.50.10.11/24
peer_route_net=10.50.20.0/24
peer_route_gw=10.50.10.254

[lan_b:vars]
segment_iface=enp8s0
segment_addr=10.50.20.12/24
peer_route_net=10.50.10.0/24
peer_route_gw=10.50.20.254

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
ansible_python_interpreter=/usr/bin/python3
