[vyos_router]
node1 ansible_host=10.100.31.10 ansible_user=vyos

[vlan_hosts]
node2 ansible_host=10.100.31.11 vlan_id=10 vlan_subnet=192.168.10.0/24 vlan_ip=192.168.10.2/24 peer_subnet=192.168.20.0/24 gateway_ip=192.168.10.1
node3 ansible_host=10.100.31.12 vlan_id=20 vlan_subnet=192.168.20.0/24 vlan_ip=192.168.20.2/24 peer_subnet=192.168.10.0/24 gateway_ip=192.168.20.1

[vlan_hosts:vars]
ansible_user=antrieb
ansible_become=yes
ansible_become_method=sudo
ansible_python_interpreter=/usr/bin/python2

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
