#!/usr/bin/env python3
"""Generate jobs/INDEX.md from saved job artifacts; optionally record runner state."""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import fcntl
import json
import os
from pathlib import Path
import tempfile
import tomllib
from urllib.parse import quote


def read(path: Path) -> dict:
    try:
        value = tomllib.loads(path.read_text()) if path.suffix == '.toml' else json.loads(path.read_text())
        return value if isinstance(value, dict) else {}
    except (OSError, ValueError):
        return {}


def atomic_write(path: Path, content: str) -> None:
    fd, temporary = tempfile.mkstemp(prefix='.' + path.name, dir=path.parent)
    try:
        with os.fdopen(fd, 'w') as handle:
            handle.write(content)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def cell(value) -> str:
    return str(value if value is not None and value != '' else 'unknown').replace('|', '\\|').replace('\n', ' ')


def settings(job: Path, execution: dict, variant: dict) -> dict:
    config = read(job / 'config.json')
    agents = config.get('agents') or [{}]
    agent = agents[0]
    kwargs = agent.get('kwargs') or {}
    verifier = config.get('verifier', {}).get('kwargs') or {}
    result = {
        'model': agent.get('model_name'), 'agent_name': kwargs.get('agent_name'),
        'reasoning_effort': kwargs.get('reasoning_effort'),
        'execution_mode': kwargs.get('execution_mode'), 'service_tier': kwargs.get('service_tier'),
        'agent_timeout_sec': kwargs.get('timeout_sec'),
        'evaluator_model': verifier.get('model'),
        'evaluator_reasoning_effort': verifier.get('reasoning_effort'),
        'transport': variant.get('run', {}).get('transport'),
    }
    result.update({k: v for k, v in variant.get('run', {}).items() if v is not None})
    result.update(execution.get('parameters', {}))
    return result


def status(result: dict, state: dict) -> str:
    if state.get('status') in ('failed', 'interrupted'):
        return state['status']
    stats = result.get('stats') or {}
    if stats.get('n_running_trials'):
        return 'running'
    if stats.get('n_errored_trials'):
        return 'errors'
    if stats.get('n_cancelled_trials'):
        return 'cancelled'
    total = result.get('n_total_trials', 0)
    if total and stats.get('n_completed_trials', 0) == total:
        return 'completed'
    if result.get('finished_at'):
        return 'incomplete'
    if state.get('status') == 'finished':
        return 'finished; no complete result'
    return state.get('status') or ('unfinished' if result else 'pending / no result')


def render(root: Path) -> str:
    groups = []
    count = 0
    for scenario in sorted(root.iterdir()):
        if not scenario.is_dir() or len(scenario.name) != 4 or not scenario.name.isdigit():
            continue
        for batch in sorted(scenario.iterdir(), reverse=True):
            if not batch.is_dir():
                continue
            jobs = sorted(p for p in batch.iterdir() if p.is_dir() and
                          any((p / name).is_file() for name in ('variant.toml', 'config.json', 'result.json')))
            if jobs:
                groups.append((scenario.name, batch, jobs))
                count += len(jobs)
    lines = ['# Job index — GENERATED', '',
             '<!-- GENERATED by scripts/generate_job_index.py. Do not edit manually. -->', '',
             f'Generated at {datetime.now(timezone.utc).isoformat(timespec="seconds")}.', '',
             f'**{count} jobs · {len(groups)} execution batches · {len({s for s, _, _ in groups})} scenarios.**', '',
             'One row per job; its unique key is scenario / batch / task. Unknown means unrecorded.',
             'Completed describes execution, not a passing reward. Running states reflect the last recorded update.',
             'Regenerate: `python3.11 scripts/generate_job_index.py`.', '']
    for scenario, batch, jobs in groups:
        scope = batch.relative_to(root).as_posix()
        execution = read(batch / 'execution.toml')
        lines += [f'## Scenario {scenario} · {batch.name}', '', f'[{len(jobs)} jobs]({quote(scope)}/)']
        if execution:
            lines += [f' · [Execution settings and task revisions]({quote(scope)}/execution.toml)',
                      f' · Configuration fingerprint: `{execution.get("configuration_fingerprint", "unknown")}`']
        if (batch / 'prompt').is_file():
            lines += [f' · [Additional prompt]({quote(scope)}/prompt) · SHA-256: `{execution.get("parameters", {}).get("prompt_sha256", "unknown")}`']
        lines += ['', '| Task / job | OS | Language | Status | Agent / model | Transport / mode | Reasoning / tier | Evaluator / reasoning | Timeout (s) | Attempts completed / total | Task / prompt revision |',
                  '| --- | --- | --- | --- | --- | --- | --- | --- | ---: | --- | --- |']
        for job in jobs:
            variant = read(job / 'variant.toml')
            result = read(job / 'result.json')
            state = read(job / 'index-state.json')
            params = settings(job, execution, variant)
            revision = execution.get('tasks', {}).get(job.name) or execution.get('recorded_task_digests', {}).get(job.name)
            revision = ('task:' + revision[:19]) if revision else 'prompt:' + variant.get('prompt', {}).get('sha256', 'unknown')[:12]
            rel = quote(job.relative_to(root).as_posix())
            name = f'[{cell(job.name)}]({rel}/)'
            if (job / 'variant.toml').is_file():
                name += f' · [variant]({rel}/variant.toml)'
            stats = result.get('stats') or {}
            total = result.get('n_total_trials', params.get('n_attempts'))
            fields = [cell(variant.get("os")), cell(variant.get("language")), status(result, state),
                      f'{cell(params.get("agent_name"))} / {cell(params.get("model"))}',
                      f'{cell(params.get("transport"))} / {cell(params.get("execution_mode"))}',
                      f'{cell(params.get("reasoning_effort"))} / {cell(params.get("service_tier"))}',
                      f'{cell(params.get("evaluator_model"))} / {cell(params.get("evaluator_reasoning_effort"))}',
                      cell(params.get('agent_timeout_sec')),
                      f'{stats.get("n_completed_trials", 0)} / {cell(total)}', revision]
            lines.append('| ' + name + ' | ' + ' | '.join(fields) + ' |')
        lines.append('')
    return '\n'.join(lines)


def generate(root: Path, job: Path | None = None, new_status: str | None = None,
             exit_code: int | None = None) -> None:
    root = root.resolve()
    root.mkdir(parents=True, exist_ok=True)
    # Serialize the snapshot as well as its replacement across concurrent runners.
    with (root / '.index.lock').open('a') as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        if job is not None:
            job = job.resolve()
            if not job.is_relative_to(root) or not job.is_dir():
                raise ValueError('Job must be an existing directory within jobs-root')
            state = {'status': new_status, 'updated_at': datetime.now(timezone.utc).isoformat(),
                     'exit_code': exit_code}
            atomic_write(job / 'index-state.json', json.dumps(state, indent=2) + '\n')
        atomic_write(root / 'INDEX.md', render(root))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--jobs-root', type=Path, default=Path(__file__).resolve().parents[1] / 'jobs')
    parser.add_argument('--job', type=Path)
    parser.add_argument('--status', choices=['running', 'finished', 'failed', 'interrupted'])
    parser.add_argument('--exit-code', type=int)
    args = parser.parse_args()
    if bool(args.job) != bool(args.status):
        parser.error('--job and --status must be supplied together')
    generate(args.jobs_root, args.job, args.status, args.exit_code)


if __name__ == '__main__':
    main()
