[router]
node1 ansible_host=10.100.112.10 ansible_user=vyos ansible_ssh_private_key_file=~/.ssh/cluster_key ansible_become=true ansible_become_method=sudo

[lan_a]
node2 ansible_host=10.100.112.11 ansible_user=root ansible_ssh_private_key_file=~/.ssh/cluster_key

[lan_b]
node3 ansible_host=10.100.112.12 ansible_user=root ansible_ssh_private_key_file=~/.ssh/cluster_key

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3
ansible_become=false
ansible_connection=ssh
